from django.urls import path
from .views import (add_drug, add_to_cart, category_create, category_delete, category_list, category_update, change_password,
                    dashboard, drug_update, expiring_drugs, finalize_sale, generate_receipt, packaging_type_create,
                    packaging_type_delete, packaging_type_list, packaging_type_update, password_change_done, remove_item,
                    sale_detail, sales_list, search_drug, stock_delete, stock_detail, stock_list, supplier_create, supplier_delete,
                    supplier_list, supplier_update, update_cart_item, user_login, user_logout, register, view_cart)

urlpatterns = [
    path('add_drug/', add_drug, name='add_drug'),
    path('expiring_drugs/', expiring_drugs, name='expiring_drugs'),
    path('suppliers/', supplier_list, name='supplier_list'),
    path('suppliers/create/', supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/update/', supplier_update, name='supplier_update'),
    path('suppliers/<int:pk>/delete/', supplier_delete, name='supplier_delete'),
    path('categories/', category_list, name='category_list'),
    path('categories/create/', category_create, name='category_create'),
    path('categories/<int:pk>/update/', category_update, name='category_update'),
    path('categories/<int:pk>/delete/', category_delete, name='category_delete'),
    path('packaging_types/', packaging_type_list, name='packaging_type_list'),
    path('packaging_types/create/', packaging_type_create, name='packaging_type_create'),
    path('packaging_types/<int:pk>/update/', packaging_type_update, name='packaging_type_update'),
    path('packaging_types/<int:pk>/delete/', packaging_type_delete, name='packaging_type_delete'),
    path('stock/', stock_list, name='stock_list'),
    path('stock/<int:pk>/', stock_detail, name='stock_detail'),
    path('stock/<int:pk>/delete/', stock_delete, name='stock_delete'),
    path('drugs/<int:pk>/update/', drug_update, name='drug_update'),
    path('register/', register, name='register'),
    path('', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('change_password/', change_password, name='change_password'),
    path('password_change/done/', password_change_done, name='password_change_done'),
    path('search_drug/', search_drug, name='search_drug'),
    path('add_to_cart/<int:drug_id>/', add_to_cart, name='add_to_cart'),
    path('view_cart/', view_cart, name='view_cart'),
    path('finalize_sale/', finalize_sale, name='finalize_sale'),
    path('remove_item/<int:item_id>/', remove_item, name='remove_item'),
    path('cart/update/<int:item_id>/', update_cart_item, name='update_cart_item'),
    path('sales/', sales_list, name='sales_list'),
    path('sale/<int:pk>/', sale_detail, name='sale_detail'),
    path('dashboard/', dashboard, name='dashboard'),
    path('receipt/<int:sale_id>/', generate_receipt, name='generate_receipt'),
  
]
